rvm:
 - 2.4.9
 - 2.5.7
 - 2.6.5
install:
  - 'travis_retry bundle install'
script: 'bundle exec rspec spec'
gemfile:
  - Gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
# Move to containerized travis, see http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false
